# Generated by Django 5.1.7 on 2025-04-27 02:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bebras', '0002_attempt_correct_count_attempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_no_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='fixed_penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='penalty_by_difficulty',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='penalty_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('by_difficulty', 'By Difficulty')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='points_per_difficulty',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='ScoringConfiguration',
        ),
    ]
