# Generated by Django 5.1.7 on 2025-07-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_bebras', '0007_answer_is_correct_answer_question_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correct',
            new_name='is_correct_manual',
        ),
    ]
