# Generated by Django 5.1.7 on 2025-07-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bebras', '0008_rename_is_correct_answer_is_correct_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Maximum number of attempts allowed for this test per student.'),
        ),
    ]
