# Generated by Django 5.1.7 on 2025-07-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_bebras', '0009_test_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='assigned_groups',
        ),
    ]
